exclude:
- CNAME
permalink: /blog/:year/:month/:day/:title.html

prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
